=== ElenaDelLla/1DAW/Lenguaje de Marcas/Tercer Trimestre/XML/5.5 Jugadores/ejemplo2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="equipos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="equipo">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="jugadores" minOccurs="1" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="jugador" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string"></xs:element>
                                                    <xs:element name="fechaNacimiento" type="xs:string" ></xs:element>
                                                    <xs:element name="altura" type="xs:double"></xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="numero" type="xs:integer" use="required"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="nombreEq" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ElenaDelLla/1DAW/Lenguaje de Marcas/Tercer Trimestre/XML/5.5 Jugadores/jugadores.xml
<?xml version="1.0"?>

<equipos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejemplo2.xsd">
<equipo nombreEq="Estudiantes">
<jugadores>
<jugador numero="12">
<nombre>Pedro</nombre>
<fechaNacimiento>12-12-1987</fechaNacimiento>
<altura>187</altura>
</jugador>
<jugador numero="17">
<nombre>Roberto</nombre>
<fechaNacimiento>10-02-1985</fechaNacimiento>
<altura>183</altura>
</jugador>
</jugadores>
</equipo>
</equipos>
