=== ElenaDelLla/1DAW/Lenguaje de Marcas/Tercer Trimestre/XML/5.4 Pedido/esquema_pedido.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="pedido">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="producto" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:choice>
                            <xs:element name="cuaderno">
                                <xs:complexType>
                                    <xs:attribute name="num_hojas" type="xs:int" use="optional"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="lÃ¡piz" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence minOccurs="1" maxOccurs="1">
                                        <xs:element name="numero" use= "optional">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                            <xs:minInclusive value="100"></xs:minInclusive>
                                            <xs:maxInclusive value="250"></xs:maxInclusive>
                                            </xs:restriction>
                                        </xs:simpleType>
                                        
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element> 
                            <xs:element name="libro">
                                <xs:complexType>
                                    <xs:attribute name="titulo" type="xs:string"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== ElenaDelLla/1DAW/Lenguaje de Marcas/Tercer Trimestre/XML/5.4 Pedido/5.4.xml
<?xml version="1.0" encoding="UTF-8"?>

<pedido xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="esquema_pedido.xsd">
    <producto>
        <lápiz>
            <numero>1</numero>    
        </lápiz>
    </producto>
    <producto>
        <libro titulo="Hola"></libro>
    </producto>
    <producto>
        <cuaderno num_hojas="3"></cuaderno>
    </producto>
</pedido>
